command: run
logLevel: 0
netPath: w/net2.graph
datasetTrainingPath: data/mnist_train.csv 
datasetTestingPath: data/mnist_test.csv 
#datasetTestingPath: dataset/mnist_test_10.csv
#datasetTrainingPath: dataset/mnist_train_100.csv
dataset: mnist
settings:
    lr: 0.01 
    alpha: 0.5 
    batchSize: 128 
    maxEpoch: 30
    minError: 0.01
#strategy: dropoutbitset

