command: run
logLevel: 0
netPath: w/net2.graph
datasetTrainingPath: dataset/mnist_train_100.csv
datasetTestingPath: dataset/mnist_test_10.csv
dataset: mnist
settings:
    lr: 0.1
    alpha: 0.1 
    batchSize: 10
    maxEpoch: 3000
    minError: 0.01
