command: run
netType: neural
logLevel: 0
netPath: w/net2.graph
datasetTrainingPath: data/mnist_train.csv 
datasetTestingPath: data/mnist_test.csv 
dataset: mnist
settings:
    lr: 0.1 #0.01
    alpha: 0.7 #0.5
    batchSize: 64 
    maxEpoch: 10
    minError: 0.01
#strategy: dropoutbitset

